# Workflow to automate creation and updating of release branches
name: Release Branching

# Trigger on tags created by TeamCity
on:
  create:
    tag:
      - '*'

jobs:
  branch_release:
    # if: github.event.sender.login == 'labkey-teamcity'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Hub
      uses: Geertvdc/setup-hub@v1.0.0

    - name: Create branches and PRs
      run: .github/workflows/scripts/branch_release.sh
      env:
        TAG: ${{ github.event.ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
